# Generated by Django 5.0.1 on 2024-03-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmadmin', '0001_initial'),
        ('farmer', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermachineryorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellingproducts'),
        ),
        migrations.AddField(
            model_name='customerproductorder',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmadmin.customerdetails'),
        ),
        migrations.AddField(
            model_name='customerproductorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.addproduct'),
        ),
    ]
