# Generated by Django 5.0.1 on 2024-03-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmername', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sendToolOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField(max_length=50)),
                ('usertype', models.CharField(choices=[('farmer', 'Farmer'), ('worker', 'Worker')], default='Farmer', max_length=50)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='addProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productimage', models.ImageField(upload_to='')),
                ('description', models.CharField(default='none', max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('farmerregister_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerregister')),
            ],
        ),
        migrations.CreateModel(
            name='sendJobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('payperday', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('farmerregister_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerregister')),
                ('workerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.workerregister')),
            ],
        ),
        migrations.CreateModel(
            name='sendRentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nooftools', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('farmerregister_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerregister')),
            ],
        ),
    ]
