# Generated by Django 5.0.1 on 2024-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workerregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workername', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('phoneno', models.BigIntegerField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
