# Generated by Django 5.0.1 on 2024-03-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellerregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField()),
                ('address', models.TextField(max_length=50)),
                ('shopname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='rentTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('timage', models.ImageField(upload_to='')),
                ('description', models.CharField(default='none', max_length=50)),
                ('priceperday', models.FloatField(max_length=50)),
                ('nooftools', models.IntegerField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('sellerregister_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerregister')),
            ],
        ),
        migrations.CreateModel(
            name='sellingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pimage', models.ImageField(upload_to='')),
                ('pcategory', models.CharField(max_length=20)),
                ('description', models.CharField(default='none', max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('sellerregister_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerregister')),
            ],
        ),
        migrations.CreateModel(
            name='sendproductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField(max_length=50)),
                ('usertype', models.CharField(choices=[('seller', 'Seller'), ('worker', 'Worker')], default='Seller', max_length=50)),
                ('quantity', models.IntegerField()),
                ('phoneno', models.BigIntegerField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.addproduct')),
            ],
        ),
    ]
